name: build

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:

  # Build versioned releases. We don't push these one every build.
  build-versions:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [amd64, arm32v6, arm64v8]
        version: ["6.0", "5.0"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: bash -x ../build.sh ${{ matrix.arch }}
        working-directory: ${{ matrix.version }}

  # Build for master. We push these on every release to make sure they
  # are up to date.
  build-master:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [amd64, arm32v6, arm64v8]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: bash -x ../build.sh ${{ matrix.arch }}
        working-directory: master
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: docker push jasonish/suricata:master-${{ matrix.arch }}

  push:
    runs-on: ubuntu-20.04
    needs: [build-master]
    steps:
      - run: echo "All containers built."
