name: nightly

on:
  schedule:
    # 3:33am wherever this is run...
    - cron: "33 3 * * *"

jobs:
  build-master-amd64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # This enables the ability to execute Arm binaries for us.
      - uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: ../build.sh amd64
        working-directory: master
      - run: docker push jasonish/suricata:master-amd64 
     
