name: nightly

on:
  schedule:
    # 3:33am wherever this is run...
    - cron: "33 19 * * *"

jobs:
  build-master:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [amd64, arm32v6, arm64v8]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: bash -x ../build.sh ${{ matrix.arch }}
        working-directory: master
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: docker push jasonish/suricata:master-${{ matrix.arch }}
